plugins { id 'com.android.application' }
android {
    namespace 'com.gunzdev.app'
    compileSdk 34
    defaultConfig {
        applicationId 'com.gunzdev.app'
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }
    buildTypes { release { minifyEnabled false } }
    compileOptions { sourceCompatibility JavaVersion.VERSION_1_8; targetCompatibility JavaVersion.VERSION_1_8 }
    lint { abortOnError false; checkReleaseBuilds false }
}
dependencies {
    implementation 'androidx.core:core:1.12.0'
    implementation 'com.android.tools.build:apksig:7.4.2'
}
